playbook.yml
=> playbook file

netlify.toml
=> added 404 redirects to netlify.toml file

antora-playbook.yml
=> rebuild site with new 6.3 branch added

antora-playbook.yml, home/antora.yml, home/modules/ROOT/pages/index.adoc
=> testing top landing page

antora-playbook.yml
=> added start page to playbook

home/modules/ROOT/pages/index.adoc
=> another home page tweak

antora-playbook.yml
=> tweaking playbook for 404

antora-playbook.yml, package.json
made logging silent in playbook
=> updated package.json to point to latest antora alpha and disable logging

antora-playbook.yml
=> tweaked playbook runtime section to add silent logging

antora-playbook.yml
=> set logging to error

build-snippets.js
=> new snippet script

build-snippets.js
=> updated snipppets script

antora-playbook.yml
=> updated playbook to build 7.0 branch

antora-playbook.yml
=> added indexify to make urls appear as directories

antora-playbook.yml
=> fixed playbook for indexify to make urls appear as directories

netlify.toml
=> added global redirect for old docs path

netlify.toml
=> another redirect attempt

netlify.toml
=> another try

antora-playbook.yml
=> updated playbook to include 7.1 branch

antora-playbook.yml
=> changed back to normal url ending for each page

netlify.toml
=> redirect home queries to software docs home

netlify.toml
=> redirect for algolia search requests

antora-playbook.yml
=> updated playbook

netlify.toml
=> site-wide redirect for august cloud

netlify.toml
=> added redirects

netlify.toml
=> updated directory-level redirects

netlify.toml
=> redirects from 5.0 - 5.3 to 6.0

netlify.toml
=> redirect for dev docs site

netlify.toml
=> updated redirects file to fix broken link to sw dev docs

netlify.toml
=> redirect to developer docs site

netlify.toml
=> another redirect

netlify.toml
=> updated the redirects to add one for product network connectivity

netlify.toml
=> added redirect for latest link in 404

netlify.toml
=> updated redirects for netlify address to resolve to actual domain

netlify.toml
=> redirect for embed viz

netlify.toml
=> updated redirects

netlify.toml
=> renamed files redirects through page 3

netlify.toml
=> renamed files through page 5

netlify.toml
=> more tweaks

netlify.toml
=> more redirect tests

netlify.toml
=> MORE TESTING

netlify.toml
=> redirect for 6.3.1cu4

netlify.toml
=> more redirects

netlify.toml
=> complete 7.0 redirects

netlify.toml
=> 6.3 redirects and more

netlify.toml
=> test of brute for latest redirect

netlify.toml
=> fingers crossed

netlify.toml
=> updated redirect for sw tse docs

netlify.toml
=> site-wide redirect for 7.0.1.CU1

netlify.toml
=> another redirect test

netlify.toml
=> 7.1 redirect for snowflake connection details page

netlify.toml
=> 7.0: redirect

netlify.toml
=> 7.0.1: more redirects

robots.txt
=> added robots.txt file for algolia

home/modules/ROOT/pages/robots.txt
=> another robots attempt

netlify.toml
=> 7-0-1-cu1-redirects

netlify.toml
=> nother test

netlify.toml
=> another test

netlify.toml
=> never mind

netlify.toml
=> fixed redirect for customer

netlify.toml
=> added global redirects for 7.0.1.jun.sw and 7.0.0.mar.sw

antora-playbook.yml
=> set extension style to make sure .html is used

antora-playbook.yml
=> testing with html extension dropped

antora-playbook.yml
=> set back to dropping .html

antora-playbook.yml
=> setting .html extension back on

antora-playbook.yml
=> removed .html extension

antora-playbook.yml
=> changed to indexify

antora-playbook.yml
=> reset extensions back to normal

antora-playbook.yml
=> added back in drop of html extension

antora-playbook.yml
=> revert to old build path in playbook

netlify.toml
=> added content security policy

netlify.toml
=> redo of republish of site with csp policy

netlify.toml
=> undid security policy for now

netlify.toml
=> testing new security policy

home/antora.yml, netlify.toml
=> updagted redirects

netlify.toml
=> redirect to home fix attempt

antora-playbook.yml
=> 7.2 GA: added 7.2 to playbook for 7.2 ga

netlify.toml
=> updated 7.1 to latest redirects to point to 7.1

netlify.toml
=> redirect for 7-1-1

netlify.toml
=> nutha redirecta

home/modules/ROOT/pages/index.adoc
=> updated cloud verbiage on landing page

antora-playbook.yml
=> added google analytics

netlify.toml
=> fixed latest directory-level redirects

home/modules/ROOT/pages/survey_thanks.adoc
=> survey thanks

home/modules/ROOT/pages/whats-new-cloud.adoc
=> whats new test

home/modules/ROOT/pages/whats-new-cloud.adoc
=> fixed links on what's new to point to 8.0.0.cl

home/modules/ROOT/pages/whats-new-cloud.adoc
=> testing embed

build-snippets.js
=> tweak to build snippets file

home/modules/ROOT/pages/whats-new-cloud.adoc
=> fixed final broken link on what's new

home/modules/ROOT/partials/whats-new-8-0-0-cl.adoc
=> tweak to 8-0-0-cl whats new

home/modules/ROOT/pages/whats-new-cloud.adoc, home/modules/ROOT/partials/whats-new-8-0-0-cl.adoc
=> more tweaks to what's new format

home/modules/ROOT/partials/whats-new-8-0-0-cl.adoc
=> what's new version label

home/modules/ROOT/partials/whats-new-8-0-0-cl.adoc
=> change in what's new label

netlify.toml
=> one more link fix

netlify.toml
=> fixed netlify.toml file

netlify.toml
=> anutha redirect

home/modules/ROOT/pages/index.adoc
=> added what's new in 8.0.0.cl to landing page

home/modules/ROOT/pages/index.adoc
=> added what's new in 8.0.0.cl to landing page with heading

home/modules/ROOT/pages/index.adoc
=> another attempt at adding the what's new to the landing page

home/modules/ROOT/pages/index.adoc
=> anutha test

home/modules/ROOT/pages/index.adoc
=> what's new on landing page

home/modules/ROOT/pages/index.adoc
=> testinggit add --all

home/modules/ROOT/pages/index.adoc
=> fixed one wrong link in what's new on landing page

home/antora.yml
=> testing home antora.yml

antora-playbook.yml, netlify.toml
=> redirects for 8.2.0.cl to latest

antora-playbook.yml
=> Publishing 7.1 and 7.2 rest api docs from dev docs repo

antora-playbook.yml
=> 8.2.0.cl: doc publishing

antora-playbook.yml, netlify.toml
=> fixed redirects

antora-playbook.yml, netlify.toml
=> updated playbook to publish 8.3.0.cl

antora-playbook.yml
=> annotated some sections in the playbook

netlify.toml
=> 7-2-1 redirects

netlify.toml
=> site-wide redirect 7.1.1.cu1

antora-playbook.yml
=> added 8.4.0.sw docs to playbook

netlify.toml
=> site-wide redirects for 7.1.1

antora-playbook.yml
=> added cl sub agreement adoc attribute to playbook

antora-playbook.yml, netlify.toml
=> added 8.4.0.cl to playbook

netlify.toml
=> removed 8.3.0.cl redirects

antora-playbook.yml, netlify.toml
Signed-off-by: Teresa Killmond <teresa.killmond@thoughtspot.com>
=> site ready for publishing

netlify.toml
=> updated redirects to fix 7.1 3rd-party csv downloads

antora-playbook.yml, netlify.toml
Signed-off-by: Teresa Killmond <teresa.killmond@thoughtspot.com>
=> ready to publish

netlify.toml
=> redirect 8.7.0.cl requests to 8.6.0.cl

netlify.toml
=> removed redirect from 7.2 to latest

netlify.toml
=> global redirect of 8.8.0.cl to go to 8.7.0.cl docs home

netlify.toml
Signed-off-by: Teresa Killmond <teresa.killmond@thoughtspot.com>
=> adding site-wide 7.2.1.cu1 redirect

antora-playbook.yml
=> added seekwell adoc attribute to playbook

netlify.toml
=> global redirect for 8.8.0.cl to latest

netlify.toml
=> added global redirect for 8.4.1.sw to latest

netlify.toml
=> redirect for 8.9.0.cl to latest

home/modules/ROOT/pages/index.adoc, netlify.toml
=> fixed home page link to seekwell

home/modules/ROOT/pages/survey_thanks.adoc
=> updated survey_thanks to use snippet layout

home/modules/ROOT/pages/survey_thanks.adoc
=> updated survey thanks page

netlify.toml
Signed-off-by: Teresa Killmond <teresa.killmond@thoughtspot.com>
=> adding redirects for 8.4.1.sw.cu1

netlify.toml
=> redirect for upgrade page

netlify.toml
=> 8.10.cl internal ga - redirect for 8.10.0.cl

netlify.toml
=> algolia pendo search test redirect to cloud

antora-playbook.yml, netlify.toml
=> 9.0.0.cl to latest redirect

netlify.toml
=> fix for redirect

antora-playbook.yml
=> 8.10.0.cl docs publishing

netlify.toml
=> removed old 8.9.0.cl redirect

netlify.toml
=> test rewrite for cloud help

antora-playbook.yml, netlify.toml
=> publish 8.8.1.sw docs

netlify.toml
=> removed another redirect

netlify.toml
=> new rewrites for index_help files

antora-playbook.yml, netlify.toml
Also includes redirects for prod links to docs
**Release announcement:**
Mudedla Bharat
[5:36 AM](https://thoughtspot.slack.com/archives/C88GNM2UT/p1696682180317109)
:tada::tada:Announcing GA of 9.5.0.sw Software Release:tada::tada:
Hello Team, Happy to announce next sw GA release- 9.5.0.sw.
**Jira list for release:**
https://thoughtspot.atlassian.net/issues/?filter=44704
=> SCAL-176190 - publish 9.5.0.sw documentation

antora-playbook.yml, netlify.toml
scal-152265
scal-149212
scal-132902
scal-79850
scal-160779
scal-150635
scal-138404
scal-158410
scal-157152
scal-154258
scal-152750
scal-158049
scal-139411
=> 9 6 0 cl publish

antora-playbook.yml
=> republish 9.5.0.cl docs for gcp customers

netlify.toml
at request of Carolina Antonio and Azim (Azimuddin Mohammed).
=> SCAL-184212 - update hidden version for Canadian tire to 9.3.0.cl

antora-playbook.yml, netlify.toml
publish 9.8.0.cl documentation
=> publishing 9.8.0.cl

netlify.toml
Per request from Raji Marimuthu for Gilead (customer)
=> SCAL-189428 - redirects for gilead 9.8.0.cl

netlify.toml
redirect requests for 9.10.5.cl release notes to 9.10.0.cl release notes until cust prod cluster upgrades.
=> SCAL-199483 - change 9.11 to 9.10.5 for help redirect

antora-playbook.yml, netlify.toml
minor fix to playboook. No content changes.
=> SCAL-202380 - publish 9.10.5.cl documentation

antora-playbook.yml, netlify.toml
Content jiras in the 9.8.0.sw release:
- scal-138404
- scal-172513
- scal-152750
- scal-158463
- scal-154154
- scal-174031
- scal-161459
- scal-161857
- SCAL-160779
- scal-158469
- scal-154258
- SCAL-172330
- scal-150635
- scal-139411
- scal-165262
- scal-158410
- scal-66335
- scal-163617
- scal-140692
- scal-79850
- scal-164909
- scal-166159
- scal-166160
- scal-166161
- scal-136661
- scal-158463
- scal-157152
- scal-149212
- scal-119947
- scal-132902
=> SCAL-204194 - publish 9.8.0.sw docs

antora-playbook.yml, vercel.json
9.12.0.cl content jiras:
- SCAL-189664 - Remove SpotApps
- SCAL-180806 - Sort and filter columns model editor
- SCAL-203404 - Model filters limit
- SCAL-136317 - multiple configurations snowflake connections
- SCAL-201885 - data panel v2 enhancements (sets, formulas, parameters)
- SCAL-196890 - GIT integration for version control of Liveboards and Answers
- SCAL-201656 - Ask Sage
- SCAL-201644 - Forecasting
- SCAL-201645 - Remember personalized columns in change analysis
- SCAL-201646 - Drill down in change analysis
- SCAL-201647, SCAL-201649 - ThoughtSpot Sync
- SCAL-202909 - Sage Coach
- SCAL-201640 - Collibra integration
- SCAL-201825 - Support for Excel (XLSX) attachments in Scheduled Liveboards
- SCAL-201822 - Show underlying data sources
- SCAL-201823 - Filters available for …
=> Publish 9.12.0.cl documentation

antora-playbook.yml, vercel.json
Documentation jiras:
- SCAL-201639
- SCAL-211771
- SCAL-211956
- SCAL-201819
- SCAL-213208
- SCAL-207739
=> Publish the 10.0.0.cl docs

vercel.json
=> another fix to site

antora-playbook.yml, vercel.json
SCAL-212555
SCAL-207062
SCAL-201298
SCAL-218932
SCAL-214756
SCAL-209029
SCAL-212095
SCAL-216615
SCAL-212285
=> publish 10.1.0.cl
